import { defineEventHandler } from 'h3'
import { systemStore } from '../../utils/system-store'

export const menuData = [
  {
    id: 1,
    parentId: null,
    title: '首页',
    icon: 'HomeOutlined',
    component: '/dashboard/workplace',
    path: '/dashboard/workplace',
    name: 'DashboardWorkplace',
    keepAlive: true,
    locale: 'menu.dashboard',
  },
  {
    id: 2,
    parentId: null,
    title: 'OA办公审批',
    icon: 'AuditOutlined',
    component: 'RouteView',
    redirect: '/oa-approval/dashboard',
    path: '/oa-approval',
    name: 'OAApproval',
    keepAlive: true,
    locale: 'menu.oa-approval',
  },
  {
    id: 3,
    parentId: 2,
    title: '财务看板',
    component: '/approval/oa-module',
    path: '/oa-approval/dashboard',
    name: 'OaFinanceDashboard',
    locale: 'menu.oa-approval.dashboard',
    meta: { oaModule: 'dashboard' },
  },
  {
    id: 4,
    parentId: 2,
    title: '审批中心',
    component: '/approval/index',
    path: '/oa-approval/center',
    name: 'ApprovalCenter',
    locale: 'menu.oa-approval.center',
    meta: { approvalView: 'center' },
  },
  {
    id: 5,
    parentId: 2,
    title: '应收应付',
    component: '/approval/oa-module',
    path: '/oa-approval/receivable-payable',
    name: 'OaReceivablePayable',
    locale: 'menu.oa-approval.receivable-payable',
    meta: { oaModule: 'receivable' },
  },
  {
    id: 6,
    parentId: 2,
    title: '现金管理',
    component: '/approval/oa-module',
    path: '/oa-approval/cash',
    name: 'OaCashManagement',
    locale: 'menu.oa-approval.cash',
    meta: { oaModule: 'cash' },
  },
  {
    id: 7,
    parentId: 2,
    title: '工资管理',
    component: '/approval/oa-module',
    path: '/oa-approval/salary',
    name: 'OaSalaryManagement',
    locale: 'menu.oa-approval.salary',
    meta: { oaModule: 'salary' },
  },
  {
    id: 9,
    parentId: 2,
    title: '办公用车',
    component: '/approval/office-vehicle/index',
    path: '/oa-approval/vehicle',
    name: 'OaOfficeVehicle',
    locale: 'menu.oa-approval.vehicle',
    meta: { oaModule: 'vehicle' },
  },
  {
    id: 8,
    parentId: 2,
    title: '组织架构',
    component: '/approval/oa-module',
    path: '/oa-approval/org',
    name: 'OaOrganization',
    locale: 'menu.oa-approval.org',
    meta: { oaModule: 'org' },
  },
  {
    id: 901,
    parentId: 2,
    title: '待我审批',
    component: '/approval/index',
    path: '/oa-approval/todo',
    name: 'ApprovalTodo',
    locale: 'menu.oa-approval.todo',
    hideInMenu: true,
    meta: { approvalView: 'todo' },
  },
  {
    id: 902,
    parentId: 2,
    title: '已办审批',
    component: '/approval/index',
    path: '/oa-approval/done',
    name: 'ApprovalDone',
    locale: 'menu.oa-approval.done',
    hideInMenu: true,
    meta: { approvalView: 'done' },
  },
  {
    id: 903,
    parentId: 2,
    title: '我发起的',
    component: '/approval/index',
    path: '/oa-approval/submitted',
    name: 'ApprovalSubmitted',
    locale: 'menu.oa-approval.submitted',
    hideInMenu: true,
    meta: { approvalView: 'submitted' },
  },
  {
    id: 904,
    parentId: 2,
    title: '抄送我的',
    component: '/approval/index',
    path: '/oa-approval/cc',
    name: 'ApprovalCc',
    locale: 'menu.oa-approval.cc',
    hideInMenu: true,
    meta: { approvalView: 'cc' },
  },
  {
    id: 905,
    parentId: 2,
    title: '审批模板',
    component: '/approval/index',
    path: '/oa-approval/templates',
    name: 'ApprovalTemplates',
    locale: 'menu.oa-approval.templates',
    hideInMenu: true,
    meta: { approvalView: 'templates' },
  },
  {
    id: 906,
    parentId: 2,
    title: '业务回写',
    component: '/approval/index',
    path: '/oa-approval/business',
    name: 'ApprovalBusiness',
    locale: 'menu.oa-approval.business',
    hideInMenu: true,
    meta: { approvalView: 'business' },
  },
  {
    id: 907,
    parentId: 2,
    title: '企业微信互通',
    component: '/approval/wecom',
    path: '/oa-approval/wecom',
    name: 'WecomApprovalIntegration',
    hideInMenu: true,
  },
  {
    id: 10,
    parentId: null,
    title: '运输管理',
    icon: 'CarOutlined',
    component: 'RouteView',
    redirect: '/transport/operations',
    path: '/transport',
    name: 'Transport',
    locale: 'menu.transport',
  },
  {
    id: 101,
    parentId: 10,
    title: '运营数据',
    component: '/transport/operations',
    path: '/transport/operations',
    name: 'TransportOperations',
    locale: 'menu.transport.operations',
  },
  {
    id: 11,
    parentId: 10,
    title: '运输订单',
    component: '/transport/module',
    path: '/transport/orders',
    name: 'TransportOrders',
    locale: 'menu.transport.orders',
  },
  {
    id: 12,
    parentId: 10,
    title: '北斗监控',
    component: '/transport/gps',
    path: '/transport/tracking',
    name: 'TransportTracking',
    locale: 'menu.transport.tracking',
  },
  {
    id: 13,
    parentId: 10,
    title: '加油明细',
    component: '/transport/module',
    path: '/transport/fuel',
    name: 'TransportFuel',
    locale: 'menu.transport.fuel',
  },
  {
    id: 14,
    parentId: 10,
    title: 'ETC费用',
    component: '/transport/module',
    path: '/transport/etc',
    name: 'TransportEtc',
    locale: 'menu.transport.etc',
  },
  {
    id: 15,
    parentId: 10,
    title: '规费管理',
    component: '/transport/fees',
    path: '/transport/fees',
    name: 'TransportFees',
    locale: 'menu.transport.fees',
  },
  {
    id: 16,
    parentId: 10,
    title: '维保管理',
    component: '/transport/maintenance',
    path: '/transport/maintenance',
    name: 'TransportMaintenance',
    locale: 'menu.transport.maintenance',
  },
  {
    id: 17,
    parentId: 10,
    title: '司机薪酬',
    component: '/transport/module',
    path: '/transport/driver-payroll',
    name: 'TransportDriverPayroll',
    locale: 'menu.transport.driver-payroll',
  },
  {
    id: 18,
    parentId: 10,
    title: '车贷费用',
    component: '/transport/vehicle-loans',
    path: '/transport/vehicle-loans',
    name: 'TransportVehicleLoans',
    locale: 'menu.transport.vehicle-loans',
  },
  {
    id: 19,
    parentId: 10,
    title: '账单核对',
    component: '/transport/bill-reconciliation',
    path: '/transport/bill-reconciliation',
    name: 'TransportBillReconciliation',
    locale: 'menu.transport.bill-reconciliation',
  },
  {
    id: 190,
    parentId: 10,
    title: '基础数据',
    component: '/transport/module',
    path: '/transport/base-data',
    name: 'TransportBaseData',
    locale: 'menu.transport.base-data',
  },
  {
    id: 20,
    parentId: null,
    title: '贸易管理',
    icon: 'SwapOutlined',
    component: 'RouteView',
    redirect: '/trade/orders',
    path: '/trade',
    name: 'Trade',
    locale: 'menu.trade',
  },
  {
    id: 21,
    parentId: 20,
    title: '贸易订单',
    component: '/trade/orders',
    path: '/trade/orders',
    name: 'TradeOrders',
    locale: 'menu.trade.orders',
  },
  {
    id: 30,
    parentId: null,
    title: '酒店管理',
    icon: 'BankOutlined',
    component: '/hotel/revenue',
    path: '/hotel',
    name: 'Hotel',
    locale: 'menu.hotel',
  },
]

export const systemMenuData = [
  {
    id: 60,
    parentId: null,
    title: '系统管理',
    icon: 'SettingOutlined',
    component: 'RouteView',
    redirect: '/system/users',
    path: '/system',
    name: 'System',
  },
  {
    id: 61,
    parentId: 60,
    title: '用户管理',
    component: '/system/users',
    path: '/system/users',
    name: 'SystemUsers',
  },
  {
    id: 62,
    parentId: 60,
    title: '组织架构',
    component: '/system/organization',
    path: '/system/organization',
    name: 'SystemOrganization',
  },
  {
    id: 63,
    parentId: 60,
    title: '角色权限',
    component: '/system/roles',
    path: '/system/roles',
    name: 'SystemRoles',
  },
  {
    id: 64,
    parentId: 60,
    title: '系统字典',
    component: '/system/dictionaries',
    path: '/system/dictionaries',
    name: 'SystemDictionaries',
  },
  {
    id: 65,
    parentId: 60,
    title: '安全日志',
    component: '/system/logs',
    path: '/system/logs',
    name: 'SystemLogs',
  },
]

export default defineEventHandler((event) => {
  const token = event.req.headers.get('Authorization')
  const user = systemStore.getUserByToken(token)
  const isAdmin = user?.roles?.includes('ADMIN')
  return {
    code: 200,
    msg: '获取成功',
    data: [...menuData, ...(isAdmin ? systemMenuData : [])],
  }
})
