import { Buffer } from 'node:buffer'
import { createDecipheriv, createHash } from 'node:crypto'
import { resolve } from 'node:path'
import process from 'node:process'
import { APPROVAL_BUSINESS_MAP, approvalInitiationSource, inferApprovalBusinessType, requiredWecomDirection } from '../../shared/approval-business-catalog'
import { approvalStore } from './approval-store'
import { readJsonFile, writeJsonFile } from './json-store'
import { systemStore } from './system-store'

export type WecomSyncStatus = 'PENDING' | 'APPROVING' | 'APPROVED' | 'REJECTED' | 'REVOKED' | 'CANCELED' | 'UNKNOWN'

export interface WecomApprovalConfig {
  corpId: string
  corpSecret: string
  callbackToken: string
  callbackAesKey: string
  enabled: boolean
  initiatorUserId: string
  approverUserId: string
}

export interface WecomTemplateMapping {
  id: string
  businessType: string
  businessLabel: string
  templateId: string
  templateName: string
  direction: 'BIDIRECTIONAL' | 'WECOM_TO_CENTER' | 'CENTER_TO_WECOM'
  enabled: boolean
  titleControlId?: string
  amountControlId?: string
  expenseTypeControlId?: string
  reasonControlId?: string
  dateControlId?: string
  remarkControlId?: string
  updatedAt: string
  autoGenerated?: boolean
}

export interface WecomSyncRecord {
  id: string
  spNo: string
  localInstanceId?: string
  templateId?: string
  title?: string
  applicantName?: string
  status: WecomSyncStatus
  source: 'WECOM' | 'APPROVAL_CENTER'
  lastSyncedAt: string
  message: string
}

interface WecomState {
  config: WecomApprovalConfig
  mappings: WecomTemplateMapping[]
  records: WecomSyncRecord[]
  sync: WecomSyncState
}

export interface WecomSyncStats {
  scanned: number
  created: number
  updated: number
  skipped: number
  failed: number
  errors: string[]
}

export interface WecomSyncState {
  cursor: string
  windowStart?: number
  lastWindowEnd?: number
  lastSuccessAt?: string
  lastError?: string
  lastStats?: WecomSyncStats
}

const dataFile = process.env.WECOM_APPROVAL_DATA_FILE
  ? resolve(process.env.WECOM_APPROVAL_DATA_FILE)
  : resolve(process.env.UPLOAD_DIR || resolve(process.cwd(), 'uploads'), '.private', 'wecom-approval.json')
function emptyState(): WecomState {
  return {
    config: { corpId: '', corpSecret: '', callbackToken: '', callbackAesKey: '', enabled: false, initiatorUserId: '', approverUserId: '' },
    mappings: [],
    records: [],
    sync: { cursor: '' },
  }
}

let accessToken = ''
let accessTokenExpiresAt = 0

function state() {
  const value = readJsonFile(dataFile, emptyState())
  value.sync ||= { cursor: '' }
  value.mappings = value.mappings.map(mapping => APPROVAL_BUSINESS_MAP.has(mapping.businessType)
    ? { ...mapping, direction: requiredWecomDirection(mapping.businessType) }
    : mapping)
  return value
}

function save(value: WecomState) {
  writeJsonFile(dataFile, value)
}

function mask(value: string) {
  if (!value)
    return ''
  return value.length <= 8 ? '********' : `${value.slice(0, 4)}****${value.slice(-4)}`
}

function publicConfig(config: WecomApprovalConfig) {
  return {
    corpId: config.corpId,
    corpSecret: mask(config.corpSecret),
    callbackToken: mask(config.callbackToken),
    callbackAesKey: mask(config.callbackAesKey),
    hasCorpSecret: Boolean(config.corpSecret),
    hasCallbackToken: Boolean(config.callbackToken),
    hasCallbackAesKey: Boolean(config.callbackAesKey),
    enabled: config.enabled,
    initiatorUserId: config.initiatorUserId || '',
    approverUserId: config.approverUserId || '',
  }
}

async function requestWecom(path: string, init?: RequestInit) {
  const config = state().config
  if (!config.corpId || !config.corpSecret)
    throw new Error('请先填写企业 ID 和审批应用 Secret')
  if (!accessToken || Date.now() >= accessTokenExpiresAt) {
    const url = new URL('https://qyapi.weixin.qq.com/cgi-bin/gettoken')
    url.searchParams.set('corpid', config.corpId)
    url.searchParams.set('corpsecret', config.corpSecret)
    const response = await fetch(url)
    const result = await response.json() as any
    if (!response.ok || result.errcode)
      throw new Error(result.errmsg || `企业微信连接失败 (${result.errcode || response.status})`)
    accessToken = result.access_token
    accessTokenExpiresAt = Date.now() + Math.max(60, Number(result.expires_in || 7200) - 300) * 1000
  }
  const url = new URL(`https://qyapi.weixin.qq.com${path}`)
  url.searchParams.set('access_token', accessToken)
  const response = await fetch(url, init)
  const result = await response.json() as any
  if (!response.ok || result.errcode)
    throw new Error(result.errmsg || `企业微信接口调用失败 (${result.errcode || response.status})`)
  return result
}

function mapStatus(value: unknown): WecomSyncStatus {
  const status = Number(value)
  return ({ 1: 'PENDING', 2: 'APPROVED', 3: 'REJECTED', 4: 'CANCELED', 5: 'REVOKED', 6: 'APPROVING', 7: 'APPROVING', 10: 'APPROVING' } as Record<number, WecomSyncStatus>)[status] || 'UNKNOWN'
}

function toIsoTime(value: unknown, fallback = new Date().toISOString()) {
  const numeric = Number(value)
  if (!Number.isFinite(numeric) || numeric <= 0)
    return fallback
  return new Date(numeric < 1e12 ? numeric * 1000 : numeric).toISOString()
}

function emptyStats(): WecomSyncStats {
  return { scanned: 0, created: 0, updated: 0, skipped: 0, failed: 0, errors: [] }
}

function latestApprovalTime(records: any[] = []) {
  const timestamps = records.flatMap((record: any) => [
    record.sptime,
    record.sp_time,
    ...(record.details || []).flatMap((detail: any) => [detail.sptime, detail.sp_time]),
  ]).map(Number).filter(value => Number.isFinite(value) && value > 0)
  return timestamps.length ? toIsoTime(Math.max(...timestamps)) : undefined
}

function controlValue(item: any) {
  const value = item?.value ?? {}
  if (value.text != null)
    return String(value.text)
  if (value.new_money != null)
    return Number(value.new_money)
  if (value.date?.s_timestamp) {
    return new Intl.DateTimeFormat('en-CA', {
      timeZone: 'Asia/Shanghai',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    }).format(new Date(Number(value.date.s_timestamp) * 1000))
  }
  if (value.selector?.options?.length)
    return value.selector.options.map((option: any) => option.value?.[0]?.text || option.key).filter(Boolean).join('、')
  if (value.children?.list?.length)
    return value.children.list.map((child: any) => controlValue(child)).filter(Boolean).join('、')
  return ''
}

function localizedTitle(item: any) {
  const titles = item?.title || []
  return String(titles.find((title: any) => title.lang === 'zh_CN')?.text || titles[0]?.text || item?.id || '')
}

function approvalFields(detail: any) {
  const items = detail.apply_data?.contents || detail.apply_data?.content || []
  return items.map((item: any) => ({ id: String(item.id || item.control_id || ''), title: localizedTitle(item), value: controlValue(item), control: item.control }))
}

function approvalContents(detail: any) {
  const result = new Map<string, any>()
  for (const field of approvalFields(detail)) {
    if (field.id)
      result.set(field.id, field.value)
  }
  return result
}

const userCache = new Map<string, { name: string, mobile: string, departmentIds: number[] }>()
const departmentCache = new Map<string, string>()

async function resolveWecomUser(userId: string) {
  if (!userId)
    return { name: '', mobile: '', departmentIds: [] as number[] }
  const cached = userCache.get(userId)
  if (cached)
    return cached
  try {
    const result = await requestWecom(`/cgi-bin/user/get?userid=${encodeURIComponent(userId)}`)
    const user = {
      name: String(result.name || userId),
      mobile: String(result.mobile || ''),
      departmentIds: (result.department || []).map(Number).filter(Number.isFinite),
    }
    userCache.set(userId, user)
    return user
  }
  catch {
    return { name: userId, mobile: '', departmentIds: [] as number[] }
  }
}

async function resolveDepartmentName(departmentId: string | number | undefined) {
  const id = String(departmentId || '')
  if (!id)
    return ''
  if (departmentCache.has(id))
    return departmentCache.get(id) || ''
  try {
    const result = await requestWecom(`/cgi-bin/department/get?id=${encodeURIComponent(id)}`)
    const name = String(result.department?.name || '')
    departmentCache.set(id, name)
    return name
  }
  catch {
    return ''
  }
}

async function enrichApprovalFlow(records: any[] = []) {
  return Promise.all(records.map(async (record: any) => ({
    status: mapStatus(record.sp_status),
    approvers: await Promise.all((record.details || []).map(async (detail: any) => ({
      userId: detail.approver?.userid,
      name: (await resolveWecomUser(String(detail.approver?.userid || ''))).name,
      status: mapStatus(detail.sp_status),
      actedAt: detail.sptime ? toIsoTime(detail.sptime) : undefined,
      comment: detail.speech || '',
    }))),
  })))
}

function resolveBusinessDomain(departmentName: string) {
  if (/酒店|宾馆/.test(departmentName))
    return '酒店'
  if (/运输|车队|物流/.test(departmentName))
    return '运输'
  if (/贸易|商贸/.test(departmentName))
    return '贸易'
  return '公司'
}

function xmlValue(xml: string, name: string) {
  const match = xml.match(new RegExp(`<${name}>(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?</${name}>`, 'i'))
  return match?.[1]?.trim() || ''
}

function decryptCallback(encrypted: string, aesKey: string, corpId: string) {
  const key = Buffer.from(`${aesKey}=`, 'base64')
  const decipher = createDecipheriv('aes-256-cbc', key, key.subarray(0, 16))
  decipher.setAutoPadding(false)
  const decoded = Buffer.concat([decipher.update(encrypted, 'base64'), decipher.final()])
  const pad = decoded[decoded.length - 1]
  const plain = decoded.subarray(0, decoded.length - pad)
  const messageLength = plain.readUInt32BE(16)
  const message = plain.subarray(20, 20 + messageLength).toString('utf8')
  const receiver = plain.subarray(20 + messageLength).toString('utf8')
  if (receiver !== corpId)
    throw new Error('回调企业 ID 不匹配')
  return message
}

let rangeSyncPromise: Promise<WecomSyncStats> | undefined

async function syncOneApproval(spNo: string, localInstanceId?: string) {
  if (!spNo.trim())
    throw new Error('请输入企业微信审批单号')
  const result = await requestWecom('/cgi-bin/oa/getapprovaldetail', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sp_no: spNo.trim() }) })
  const detail = result.info || result
  const applicantId = String(detail.applyer?.userid || '').trim()
  if (!applicantId)
    throw new Error('审批发起人不属于当前企业组织')

  const value = state()
  const templateId = String(detail.template_id || 'unknown')
  const fields = approvalFields(detail)
  const contents = approvalContents(detail)
  const candidateMappings = value.mappings.filter(item => item.enabled
    && item.templateId === templateId
    && item.direction === 'WECOM_TO_CENTER')
  const searchableText = [detail.sp_name, ...fields.map(field => `${field.title}:${field.value}`)].filter(Boolean).join('；')
  const inferredBusinessType = inferApprovalBusinessType(searchableText)
  let mapping = inferredBusinessType
    ? candidateMappings.find(item => item.businessType === inferredBusinessType)
    : undefined
  if (!mapping && inferredBusinessType && APPROVAL_BUSINESS_MAP.has(inferredBusinessType)) {
    const base = candidateMappings[0]
    const catalog = APPROVAL_BUSINESS_MAP.get(inferredBusinessType)!
    if (base) {
      mapping = {
        ...base,
        businessType: inferredBusinessType,
        businessLabel: catalog.label,
        autoGenerated: true,
      }
    }
  }
  if (!mapping && candidateMappings.length === 1 && APPROVAL_BUSINESS_MAP.has(candidateMappings[0].businessType))
    mapping = candidateMappings[0]
  if (!mapping)
    throw new Error(`无法根据审批事项识别业务模块：${searchableText.slice(0, 120) || templateId}`)

  const amount = mapping.amountControlId ? Number(contents.get(mapping.amountControlId) || 0) : undefined
  const status = mapStatus(detail.sp_status)
  const submittedAt = toIsoTime(detail.apply_time)
  const completedAt = latestApprovalTime(detail.sp_record)
  const applicant = await resolveWecomUser(applicantId)
  const departmentId = detail.applyer?.partyid || applicant.departmentIds[0]
  const departmentName = await resolveDepartmentName(departmentId)
  const boundUser = await systemStore.bindWecomIdentity({
    wecomUserId: applicantId,
    mobile: applicant.mobile,
    nickname: applicant.name,
    wecomDepartmentId: String(departmentId || ''),
    deptName: departmentName,
  })
  const localApplicantId = boundUser?.id ?? applicantId
  const localApplicantName = boundUser?.nickname || applicant.name
  const localDepartmentId = boundUser?.deptId || departmentId
  const localDepartmentName = boundUser?.deptName || departmentName
  const approvalFlow = await enrichApprovalFlow(detail.sp_record)
  const notifyers = await Promise.all((detail.notifyer || []).map(async (item: any) => {
    const userId = String(item.userid || item)
    return { userId, name: (await resolveWecomUser(userId)).name }
  }))
  const displayTitle = String((mapping.titleControlId && contents.get(mapping.titleControlId)) || detail.sp_name || mapping.businessLabel)
  const formData = {
    approvalType: mapping.businessLabel,
    category: mapping.autoGenerated ? '企业微信自动分类' : APPROVAL_BUSINESS_MAP.get(mapping.businessType)?.category,
    moduleName: mapping.autoGenerated ? '审批中心' : APPROVAL_BUSINESS_MAP.get(mapping.businessType)?.moduleName,
    modulePath: mapping.autoGenerated ? '/oa-approval/center' : APPROVAL_BUSINESS_MAP.get(mapping.businessType)?.modulePath,
    contentOption: mapping.expenseTypeControlId ? contents.get(mapping.expenseTypeControlId) : undefined,
    description: mapping.reasonControlId ? contents.get(mapping.reasonControlId) : undefined,
    occurredDate: mapping.dateControlId ? contents.get(mapping.dateControlId) : undefined,
    remark: mapping.remarkControlId ? contents.get(mapping.remarkControlId) : undefined,
    amount,
    businessDomain: resolveBusinessDomain(departmentName),
    departmentName: localDepartmentName,
    source: '企业微信',
    wecomSpNo: spNo,
    wecomTemplateId: templateId,
    wecomTemplateName: detail.sp_name || mapping.templateName,
    controls: fields,
    approvalFlow,
    notifyers,
    originalStatus: detail.sp_status,
  }
  const existingRecord = value.records.find(item => item.spNo === spNo)
  const record: WecomSyncRecord = {
    id: `WCS-${spNo}`,
    spNo,
    localInstanceId: localInstanceId || existingRecord?.localInstanceId,
    templateId,
    title: displayTitle,
    applicantName: applicant.name,
    status,
    source: 'WECOM',
    lastSyncedAt: new Date().toISOString(),
    message: '已从企业微信拉取最新状态',
  }

  if (mapping.autoGenerated) {
    const synced = await approvalStore.upsertExternal({
      externalKey: spNo,
      approvalType: mapping.businessLabel,
      businessType: mapping.businessType,
      businessNo: spNo,
      title: displayTitle,
      applicantId: localApplicantId,
      applicantName: localApplicantName,
      deptId: localDepartmentId,
      deptName: localDepartmentName,
      amount: Number.isFinite(amount) ? amount : undefined,
      status: status === 'UNKNOWN' ? 'APPROVING' : status,
      submittedAt,
      completedAt,
      formData,
      ccUserIds: notifyers.map(item => item.userId),
    })
    record.localInstanceId = synced.instance.id
  }
  else {
    if (!record.localInstanceId) {
      const submitted = await approvalStore.submit({
        businessType: mapping.businessType,
        approvalType: mapping.businessType,
        businessModule: formData.moduleName,
        businessId: `WECOM-${spNo}`,
        businessNo: spNo,
        title: detail.sp_name || mapping.businessLabel,
        applicantId: localApplicantId,
        applicantName: localApplicantName,
        deptId: localDepartmentId,
        deptName: localDepartmentName,
        amount: Number.isFinite(amount) ? amount : undefined,
        formData,
        ccUserIds: [],
      })
      record.localInstanceId = submitted.instance.id
    }
    if (status !== 'UNKNOWN') {
      const localStatus = status === 'CANCELED' ? 'REVOKED' : status
      await approvalStore.applyExternalStatus(record.localInstanceId, localStatus, '企业微信', spNo)
    }
  }

  record.message = existingRecord ? '企业微信状态及详情已更新' : '已从企业微信创建审批中心单据'
  value.records = [record, ...value.records.filter(item => item.spNo !== spNo)].slice(0, 500)
  save(value)
  return { record, created: !existingRecord }
}

async function performRangeSync(startTime: number, endTime: number) {
  const stats = emptyStats()
  const maxWindowSeconds = 30 * 24 * 60 * 60
  try {
    for (let windowStart = startTime; windowStart < endTime; windowStart += maxWindowSeconds) {
      const windowEnd = Math.min(endTime, windowStart + maxWindowSeconds)
      const currentState = state()
      let cursor = currentState.sync.windowStart === windowStart ? currentState.sync.cursor : ''
      do {
        const cursorState = state()
        cursorState.sync.windowStart = windowStart
        cursorState.sync.cursor = cursor
        save(cursorState)
        const response = await requestWecom('/cgi-bin/oa/getapprovalinfo', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ starttime: windowStart, endtime: windowEnd, new_cursor: cursor, size: 100 }),
        })
        const spNos = (response.sp_no_list || []).map(String).filter(Boolean)
        stats.scanned += spNos.length
        for (const spNo of spNos) {
          try {
            const synced = await syncOneApproval(spNo)
            if (synced.created)
              stats.created++
            else
              stats.updated++
          }
          catch (error: any) {
            stats.failed++
            stats.errors.push(`${spNo}: ${error?.message || '同步失败'}`)
          }
        }
        const nextCursor = String(response.new_next_cursor || response.next_cursor || '')
        cursor = nextCursor && nextCursor !== cursor ? nextCursor : ''
      } while (cursor)
      const completedState = state()
      completedState.sync.cursor = ''
      completedState.sync.windowStart = undefined
      completedState.sync.lastWindowEnd = windowEnd
      save(completedState)
    }
    const successState = state()
    successState.sync.lastSuccessAt = new Date().toISOString()
    successState.sync.lastError = undefined
    save(successState)
  }
  catch (error: any) {
    const errorState = state()
    errorState.sync.lastError = error?.message || '批量同步失败'
    save(errorState)
    throw error
  }
  finally {
    stats.errors = stats.errors.slice(0, 20)
    const finalState = state()
    finalState.sync.lastStats = stats
    save(finalState)
  }
  return stats
}

export const wecomApprovalStore = {
  getOverview() {
    const value = state()
    return { config: publicConfig(value.config), mappings: value.mappings, records: value.records.slice(0, 100), sync: value.sync }
  },

  saveConfig(input: Partial<WecomApprovalConfig>) {
    const value = state()
    value.config = {
      ...value.config,
      ...input,
      corpSecret: input.corpSecret?.includes('*') ? value.config.corpSecret : String(input.corpSecret ?? value.config.corpSecret),
      callbackToken: input.callbackToken?.includes('*') ? value.config.callbackToken : String(input.callbackToken ?? value.config.callbackToken),
      callbackAesKey: input.callbackAesKey?.includes('*') ? value.config.callbackAesKey : String(input.callbackAesKey ?? value.config.callbackAesKey),
    }
    save(value)
    accessToken = ''
    return publicConfig(value.config)
  },

  async testConnection() {
    const config = state().config
    if (!config.corpId || !config.corpSecret)
      throw new Error('请先填写企业 ID 和审批应用 Secret')
    const url = new URL('https://qyapi.weixin.qq.com/cgi-bin/gettoken')
    url.searchParams.set('corpid', config.corpId)
    url.searchParams.set('corpsecret', config.corpSecret)
    const response = await fetch(url)
    const result = await response.json() as any
    if (!response.ok || result.errcode)
      throw new Error(result.errmsg || `企业微信连接失败 (${result.errcode || response.status})`)
    accessToken = result.access_token
    accessTokenExpiresAt = Date.now() + Math.max(60, Number(result.expires_in || 7200) - 300) * 1000
    return true
  },

  saveMapping(input: Omit<WecomTemplateMapping, 'id' | 'updatedAt'> & { id?: string }) {
    if (!input.businessType || !input.templateId)
      throw new Error('业务类型和企业微信模板 ID 不能为空')
    const catalog = APPROVAL_BUSINESS_MAP.get(input.businessType)
    if (!catalog)
      throw new Error('业务类型必须从审批中心业务目录中选择')
    const value = state()
    const mapping: WecomTemplateMapping = { ...input, direction: requiredWecomDirection(input.businessType), businessLabel: catalog.label, id: input.id || `WCM-${Date.now()}`, updatedAt: new Date().toISOString() }
    const index = value.mappings.findIndex(item => item.id === mapping.id)
    if (index >= 0)
      value.mappings[index] = mapping
    else
      value.mappings.unshift(mapping)
    save(value)
    return mapping
  },

  removeMapping(id: string) {
    const value = state()
    value.mappings = value.mappings.filter(item => item.id !== id)
    save(value)
  },

  async syncApproval(spNo: string, localInstanceId?: string) {
    return (await syncOneApproval(spNo, localInstanceId)).record
  },

  async syncRange(input: { startTime?: number, endTime?: number, days?: number } = {}) {
    if (rangeSyncPromise)
      return rangeSyncPromise
    const endTime = Math.floor(Number(input.endTime || Date.now() / 1000))
    const days = Math.min(90, Math.max(1, Number(input.days || 1)))
    const startTime = Math.floor(Number(input.startTime || endTime - days * 24 * 60 * 60))
    rangeSyncPromise = performRangeSync(startTime, endTime).finally(() => {
      rangeSyncPromise = undefined
    })
    return rangeSyncPromise
  },

  async syncIncremental() {
    const value = state()
    if (!value.config.enabled)
      return emptyStats()
    const endTime = Math.floor(Date.now() / 1000)
    const startTime = value.sync.lastWindowEnd
      ? Math.max(value.sync.lastWindowEnd - 10 * 60, endTime - 24 * 60 * 60)
      : endTime - 90 * 24 * 60 * 60
    return this.syncRange({ startTime, endTime })
  },

  async pushApproval(localInstanceId: string) {
    const value = state()
    if (!value.config.enabled)
      throw new Error('请先启用企业微信审批同步')
    const detail = await approvalStore.getDetail(localInstanceId)
    const instance = detail.instance
    if (approvalInitiationSource(instance.businessType) === 'WECOM')
      throw new Error('该人事事项必须在企业微信发起，不能从管理系统重复推送')
    const systemUsers = await systemStore.listUsers({ status: 'enabled' })
    const applicant = systemUsers.find(item => String(item.id) === String(instance.applicantId))
    const creatorUserId = applicant?.wecomUserId || value.config.initiatorUserId
    if (!creatorUserId)
      throw new Error('申请人尚未绑定企业微信 UserID')
    const mapping = value.mappings.find(item => item.enabled && item.businessType === instance.businessType && item.direction === 'CENTER_TO_WECOM')
    if (!mapping)
      throw new Error('当前业务类型尚未配置可推送的企业微信模板')

    const contents: any[] = []
    if (mapping.titleControlId) {
      contents.push({ control: 'Text', id: mapping.titleControlId, value: { text: instance.title } })
    }
    if (mapping.amountControlId && instance.amount != null) {
      contents.push({ control: 'Money', id: mapping.amountControlId, value: { new_money: String(Math.round(Number(instance.amount) * 100)) } })
    }
    const processNodes = detail.nodes.map((node: any) => {
      const userIds = (node.approverIds || []).map((id: string | number) => systemUsers.find(user => String(user.id) === String(id))?.wecomUserId).filter(Boolean)
      if (!userIds.length && value.config.approverUserId)
        userIds.push(value.config.approverUserId)
      if (!userIds.length)
        throw new Error(`审批节点“${node.name}”的审批人尚未绑定企业微信 UserID`)
      return { type: 1, apv_rel: 1, userid: userIds }
    })
    const result = await requestWecom('/cgi-bin/oa/applyevent', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        creator_userid: creatorUserId,
        template_id: mapping.templateId,
        use_template_approver: 0,
        process: {
          node_list: processNodes,
        },
        apply_data: { contents },
        summary_list: [{ summary_info: [{ text: instance.title, lang: 'zh_CN' }] }],
      }),
    })
    const spNo = String(result.sp_no || '')
    if (!spNo)
      throw new Error('企业微信未返回审批单号')
    const record: WecomSyncRecord = {
      id: `WCS-${spNo}`,
      spNo,
      localInstanceId,
      templateId: mapping.templateId,
      title: instance.title,
      applicantName: instance.applicantName,
      status: 'PENDING',
      source: 'APPROVAL_CENTER',
      lastSyncedAt: new Date().toISOString(),
      message: '已从审批中心发起企业微信审批',
    }
    value.records = [record, ...value.records.filter(item => item.localInstanceId !== localInstanceId)].slice(0, 200)
    save(value)
    return record
  },

  archiveLocalRecord(localInstanceId: string, reason?: string) {
    const value = state()
    const record = value.records.find(item => item.localInstanceId === localInstanceId)
    if (!record)
      return undefined
    if (['PENDING', 'APPROVING'].includes(record.status))
      record.status = 'REVOKED'
    record.lastSyncedAt = new Date().toISOString()
    record.message = `管理系统已${record.status === 'REVOKED' ? '撤销并归档' : '作废归档'}：${reason || '管理员删除'}；企业微信保留历史记录`
    save(value)
    return record
  },

  verifySignature(signature: string, timestamp: string, nonce: string, encrypted: string) {
    const token = state().config.callbackToken
    const digest = createHash('sha1').update([token, timestamp, nonce, encrypted].sort().join('')).digest('hex')
    return Boolean(token) && digest === signature
  },

  decryptCallback(encrypted: string) {
    const config = state().config
    if (!config.callbackAesKey || !config.corpId)
      throw new Error('尚未配置回调 EncodingAESKey')
    return decryptCallback(encrypted, config.callbackAesKey, config.corpId)
  },

  async handleCallbackXml(xml: string) {
    const spNo = xmlValue(xml, 'SpNo') || xmlValue(xml, 'ApprovalNo')
    if (spNo)
      return await this.syncApproval(spNo)
    return undefined
  },

  extractEncrypted: (xml: string) => xmlValue(xml, 'Encrypt'),
}

if (process.env.NODE_ENV !== 'test') {
  const timer = setInterval(() => {
    void wecomApprovalStore.syncIncremental().catch(() => {})
  }, 5 * 60 * 1000)
  timer.unref?.()
  const initialTimer = setTimeout(() => {
    void wecomApprovalStore.syncIncremental().catch(() => {})
  }, 10 * 1000)
  initialTimer.unref?.()
}
